---
title: "Group 41 UCSB domestic grad enrollment"
author: "Chase Tarr, Sachiko Lamen"
date: "11/16/2021"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

#attaching packages

library(here)
library(tidyverse)
```

## Reading in the Data
```{r}
ucsb_grad <- read_csv(here("data", "ucsb_grad_data.csv"))
```
## Create column graph
```{r}
palette1 <- c("purple", "yellow", "maroon", "red", "lightgreen", "blue", "orange", "pink", "grey", "lightblue")

ggplot(data = ucsb_grad, aes(x = year_abbr, y = domestic_enrollment)) +
  geom_col(aes(fill = ethnicity), position = "fill") +
  labs(x = "Year", y = "Proportion of Enrollment",
       title = "Domestic Graduate Enrollment (2008 - 2019)",
       legend = "Ethnicity") +
  theme_minimal() + 
  guides(fill = guide_legend(title= "Ethnicity")) +
   scale_fill_manual (values = palette1)
```

 **Figure 1.** Each column represents a different year and colors denote ethnicity. Columns represent total enrollment population, with thickness of color band representing relative proportion of graduates enrolled.
 
